// Generated by tools/i18n.py from site.js. Do not edit by hand.
const levels = [
  {level:1,label:'Первые шаги',ages:'3\u00a0года',program:'Recreational',apparatus:'Скакалка',title:'Маленькая искра большого пути.',text:'Знакомство с\u00a0движением, координацией и\u00a0скакалкой в\u00a0игре.'},
  {level:2,label:'Свой ритм',ages:'4–5\u00a0лет',program:'Recreational',apparatus:'Скакалка, мяч',title:'Пусть ведёт любопытство.',text:'Игра и\u00a0движение, растущая уверенность и\u00a0первая дружба со\u00a0скакалкой и\u00a0мячом.'},
  {level:3,label:'Основа',ages:'6–7\u00a0лет',program:'Competitive',apparatus:'Скакалка, мяч, обруч',title:'Начинается новая глава.',text:'Скакалка, мяч и\u00a0обруч вместе: гимнастки начинают готовиться к\u00a0соревнованиям.'},
  {level:4,label:'Сила',ages:'от\u00a06\u00a0лет',program:'Competitive',apparatus:'+\u00a0булавы',title:'Место для нового вызова.',text:'Добавляются булавы, а\u00a0растяжка и\u00a0работа с\u00a0предметами остаются в\u00a0центре внимания.'},
  {level:5,label:'Выразительность',ages:'от\u00a07\u00a0лет',program:'Competitive',apparatus:'+\u00a0лента (все пять)',title:'Пусть раскроется выразительность.',text:'Лента завершает набор предметов, пока растут навыки и\u00a0гибкость.'},
  {level:6,label:'На\u00a0ковёр',ages:'от\u00a08\u00a0лет',program:'Competitive',apparatus:'Все предметы',title:'Амбиции\u00a0— на\u00a0ковёр.',text:'Путь к\u00a0серьёзной соревновательной гимнастике, уровень определяет тренер.'}
];
// Sample trial times only; the academy sets the real ones (they are not published as a class schedule).
const programs = [
  {name:'Recreational',days:['Понедельник, 17:00','Среда, 17:00']},
  {name:'Competitive',days:['Вторник, 18:00','Четверг, 18:00']},
  {name:'Stretching & Flexibility',days:['Пятница, 19:00']}
];
const age=document.querySelector('#age'),experience=document.querySelector('#experience'),path=document.querySelector('.path');
if(age&&experience&&path)path.innerHTML='<span class="path-spark" aria-hidden="true">✦</span>'+levels.map(l=>`<div class="level" data-level="${l.level}"><span class="level-number">${l.level}</span><div class="level-description"><p>${l.label}</p><small>${l.ages}</small><small class="apparatus">${l.apparatus}</small></div></div>`).join('')+'<span class="assessment-stop" hidden>Начнём с\u00a0оценки тренера</span>';
function positionSpark(){
  if(!path)return;
  const spark=path.querySelector('.path-spark'),target=path.querySelector('.level.active .level-number')||path.querySelector('.assessment-stop:not([hidden])');
  if(!target)return;
  const parent=path.getBoundingClientRect(),rect=target.getBoundingClientRect(),assessment=target.classList.contains('assessment-stop');
  const x=assessment?rect.left-parent.left-28:rect.left-parent.left+rect.width/2-10;
  const y=assessment?rect.top-parent.top+2:rect.top-parent.top-25;
  spark.style.transform=`translate(${x}px,${y}px)`;
}
function updateMatch(){
  const years=Number(age.value),competitive=experience.querySelector('[value="competitive"]');
  competitive.hidden=competitive.disabled=years<6;
  if(years<6&&experience.value==='competitive')experience.value='none';
  const assessment=years>=6||experience.value==='competitive',selected=years===3?levels[0]:levels[1];
  path.classList.toggle('needs-assessment',assessment);
  const stop=path.querySelector('.assessment-stop');stop.hidden=!assessment;
  if(assessment)stop.setAttribute('aria-current','step');else stop.removeAttribute('aria-current');
  path.querySelectorAll('.level').forEach(el=>{
    const active=!assessment&&Number(el.dataset.level)===selected.level;
    el.classList.toggle('active',active);el.classList.toggle('possible',assessment&&Number(el.dataset.level)>=3);
    if(active)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');
  });
  document.querySelector('#match-label').textContent=assessment?'Старт / Оценка тренера':`Возможный старт / Уровень\u00a0${selected.level}`;
  document.querySelector('#match-title').textContent=assessment?'У\u00a0каждого свой путь.':selected.title;
  document.querySelector('#match-copy').textContent=assessment?"Возраст\u00a0— только часть картины. Расскажите об\u00a0опыте ребёнка, и\u00a0на\u00a0пробном занятии тренер поможет подобрать уровень.":selected.text;
  document.querySelector('#experience-note').hidden=assessment||experience.value!=='some';
  Object.assign(document.querySelector('#match-cta').dataset,{program:assessment?'Competitive':'Recreational',age:years,experience:experience.value});
  positionSpark();
}
if(age&&experience&&path){age.addEventListener('change',updateMatch);experience.addEventListener('change',updateMatch);updateMatch();}
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');
function closeMenu(){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
// Under the open sheet the page is dimmed by .header:after; a tap there lands on the header itself and closes the sheet.
const header=document.querySelector('.header');
header.addEventListener('click',event=>{if(event.target===header&&nav.classList.contains('open'))closeMenu();});
const langMenu=document.querySelector('.lang-menu');
document.addEventListener('click',event=>{if(langMenu.open&&!langMenu.contains(event.target))langMenu.open=false;});
document.addEventListener('keydown',event=>{
  if(event.key!=='Escape')return;
  if(nav.classList.contains('open')){closeMenu();menu.focus();}
  if(langMenu.open){langMenu.open=false;langMenu.querySelector('summary').focus();}
});
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',()=>{const target=document.getElementById(link.hash.slice(1));if(target?.tagName==='DETAILS')target.open=true;}));

// Carry the selected program across pages, including the shared header CTA.
document.querySelectorAll('a[href]').forEach(link=>{
  const target=new URL(link.href);
  const selected=link.dataset.program||document.body.dataset.trialProgram;
  if(target.origin===location.origin&&target.hash==='#trial'&&target.pathname!==location.pathname&&selected==='Stretching & Flexibility'){
    target.searchParams.set('program','stretching');link.href=target.href;
  }
});

// Move the one fallback form into the native dialog; never clone IDs or field values.
const dialog=document.querySelector('#booking-dialog'),form=document.querySelector('#trial-form'),panel=document.querySelector('#booking-panel');
const entry=document.querySelector('#booking-entry'),confirmation=document.querySelector('#booking-confirmation'),submit=document.querySelector('#booking-submit');
const status=document.querySelector('#form-status'),summary=document.querySelector('#error-summary'),program=document.querySelector('#program'),day=document.querySelector('#preferred-day');
if(dialog&&form&&panel){
const fields=[...form.querySelectorAll('input:not([type=radio]),select')],hints=new Map(fields.map(field=>[field.id,field.getAttribute('aria-describedby')||'']));
let initialized=false,submitting=false,submissionVersion=0;
form.noValidate=true;
document.querySelector('#dialog-content').append(panel);document.querySelector('#booking-home').hidden=true;
document.querySelector('.enhanced-trial').hidden=false;document.querySelector('#trial').classList.add('enhanced');
function populateDays(){
  const previous=day.value,schedule=programs.find(p=>p.name===program.value);
  day.replaceChildren(new Option('Выберите время',''));
  (schedule?.days||[]).forEach(value=>day.add(new Option(`${value} [пример]`,value)));
  if(schedule?.days.includes(previous))day.value=previous;
}
program.addEventListener('change',populateDays);
function openBooking(link){
  if(submitting)cancelSubmission();
  if(!initialized||link.id==='match-cta'){
    const match=document.querySelector('#match-cta')?.dataset||{};
    program.value=match.program;document.querySelector('#trial-age').value=match.age;document.querySelector('#trial-experience').value=match.experience;
  }
  if(link.dataset.program)program.value=link.dataset.program;
  if(link.dataset.program==='Stretching & Flexibility'&&!initialized)document.querySelector('#trial-age').value='';
  initialized=true;populateDays();
  if(!submitting){entry.hidden=false;confirmation.hidden=true;dialog.setAttribute('aria-labelledby','booking-title');}
  closeMenu();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;
}
document.querySelectorAll('a[href="#trial"]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();openBooking(link);}));
function openTrialHash(){
  if(location.hash!=='#trial'||dialog.open)return;
  const selected=new URLSearchParams(location.search).get('program');
  openBooking({id:'',dataset:selected==='stretching'?{program:'Stretching & Flexibility'}:{}});
}
window.addEventListener('hashchange',openTrialHash);
window.addEventListener('pageshow',openTrialHash);
openTrialHash();
document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('close',()=>{if(!dialog.open&&submitting)cancelSubmission();});
dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();});
document.querySelector('#edit-booking').addEventListener('click',()=>{confirmation.hidden=true;entry.hidden=false;dialog.setAttribute('aria-labelledby','booking-title');document.querySelector('#child-name').focus();});
function errorFor(field){
  const value=field.value.trim();
  switch(field.id){
    case 'child-name':return value.length<2||value.length>50?"Введите имя ребёнка: от\u00a02 до\u00a050 символов":'';
    case 'trial-age':return !value?"Введите возраст ребёнка":!Number.isInteger(Number(value))||Number(value)<3||Number(value)>99?"Введите возраст ребёнка целым числом от\u00a03 до\u00a099":'';
    case 'trial-experience':return !['none','some','competitive'].includes(value)?"Выберите опыт ребёнка в\u00a0гимнастике":'';
    case 'program':return !programs.some(p=>p.name===value)?'Выберите программу':'';
    case 'preferred-day':return !programs.find(p=>p.name===program.value)?.days.includes(value)?'Выберите время пробного для этой программы':'';
    case 'parent':return value.length<2||value.length>80?'Введите ваше имя: от\u00a02 до\u00a080 символов':'';
    case 'phone':return value.replace(/\D/g,'').length!==10?'Введите номер телефона в\u00a0США из\u00a010\u00a0цифр':'';
    case 'email':return !value||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)?'Введите адрес эл. почты, например name@example.com':'';
    case 'consent':return !field.checked?'Отметьте согласие на\u00a0связь по\u00a0поводу пробного занятия':'';
    default:return '';
  }
}
function setError(field,message){
  const error=document.getElementById(`${field.id}-error`);error.textContent=message;error.hidden=!message;
  field.closest('.field').classList.toggle('has-error',Boolean(message));
  if(message)field.setAttribute('aria-invalid','true');else field.removeAttribute('aria-invalid');
  const describedBy=[hints.get(field.id),message?error.id:''].filter(Boolean).join(' ');
  if(describedBy)field.setAttribute('aria-describedby',describedBy);else field.removeAttribute('aria-describedby');
}
function refreshErrorSummary(){
  const list=summary.querySelector('ul');list.replaceChildren();
  fields.filter(f=>f.getAttribute('aria-invalid')==='true').forEach(field=>{
    const li=document.createElement('li'),link=document.createElement('a');link.href=`#${field.id}`;link.textContent=document.getElementById(`${field.id}-error`).textContent;
    link.addEventListener('click',event=>{event.preventDefault();field.focus();});li.append(link);list.append(li);
  });
  summary.hidden=!list.children.length;submit.classList.toggle('has-error',!summary.hidden);
}
fields.forEach(field=>field.addEventListener('input',()=>{if(field.getAttribute('aria-invalid')==='true'){setError(field,errorFor(field));refreshErrorSummary();}}));
document.querySelector('#phone').addEventListener('input',event=>{
  const input=event.target,old=input.value,caret=input.selectionStart??old.length;
  let digits=old.replace(/\D/g,'');if(digits.length===11&&digits.startsWith('1'))digits=digits.slice(1);
  if(digits.length>10)return; // Preserve invalid overlong input so validation can explain it.
  const digitsBefore=old.slice(0,caret).replace(/\D/g,'').length;
  input.value=digits.length>6?`(${digits.slice(0,3)}) ${digits.slice(3,6)}-${digits.slice(6)}`:digits.length>3?`(${digits.slice(0,3)}) ${digits.slice(3)}`:digits?`(${digits}`:'';
  let position=0,count=0;while(position<input.value.length&&count<digitsBefore){if(/\d/.test(input.value[position]))count++;position++;}input.setSelectionRange(position,position);
});
function bookingRows(){
  return [['Ребёнок',form.elements.childName.value],['Возраст',form.elements.age.value],['Опыт',form.elements.experience.selectedOptions[0].text],['Программа',program.selectedOptions[0].text],['Время',`${day.value} [пример]`],['Оплата',form.elements.payment.value==='online'?'10\u00a0$ онлайн (в\u00a0прототипе здесь будет Stripe Checkout)':'10\u00a0$ в\u00a0академии'],['Ваше имя',form.elements.parent.value],['Телефон',form.elements.phone.value],['Эл. почта',form.elements.email.value]];
}
function resetLoading(){
  fields.forEach(field=>field.disabled=false);submitting=false;submit.disabled=false;form.removeAttribute('aria-busy');
  form.querySelector('.submit-label').textContent='Записаться';form.querySelector('.spinner').hidden=true;form.querySelector('.submit-arrow').hidden=false;
}
function cancelSubmission(){submissionVersion++;resetLoading();status.textContent='';}
function showConfirmation(rows){
  const list=document.querySelector('#booking-summary');list.replaceChildren();
  rows.forEach(([label,value])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;list.append(dt,dd);});
  entry.hidden=true;confirmation.hidden=false;dialog.setAttribute('aria-labelledby','confirmation-title');dialog.scrollTop=0;if(dialog.open)document.querySelector('#confirmation-title').focus();
}
form.addEventListener('submit',async event=>{
  event.preventDefault();if(submitting)return;
  fields.forEach(field=>setError(field,errorFor(field)));refreshErrorSummary();
  // In the dialog, keep the title in view: scroll to top, then focus the summary without scrolling.
  if(!summary.hidden){status.textContent='Проверьте отмеченные поля';if(dialog.open){dialog.scrollTop=0;summary.focus({preventScroll:true});}else summary.focus();return;}
  const version=++submissionVersion,rows=bookingRows();
  submitting=true;submit.disabled=true;form.setAttribute('aria-busy','true');
  form.querySelector('.submit-label').textContent='Отправляем…';form.querySelector('.spinner').hidden=false;form.querySelector('.submit-arrow').hidden=true;status.textContent='Готовим подтверждение прототипа…';fields.forEach(field=>field.disabled=true);
  try{
    // Local-only simulation. No network request, storage, email, or payment.
    await new Promise(resolve=>setTimeout(resolve,650));if(version!==submissionVersion)return;showConfirmation(rows);status.textContent='';
  }catch{status.textContent='Не\u00a0получилось отправить. Данные сохранены, попробуйте ещё раз.';submit.classList.add('has-error');}
  finally{
    if(version===submissionVersion)resetLoading();
  }
});

}

// Layout-only geometry; CSS drives the draw/rewind. No scroll handler.
const main=document.querySelector('main'),ribbon=document.querySelector('.page-ribbon'),ribbonLine=ribbon?.querySelector('path');
const ribbonTiming=document.createElement('style');if(ribbon)document.head.append(ribbonTiming);
// Satin ribbon along the same path: width follows |cos(twist)| so it narrows where it flips,
// the back side is paler, edges darken, flats get a highlight. Consecutive quads of one colour share a path,
// so later parts of the ribbon still draw over earlier ones where it crosses itself.
const satin=ribbon?.querySelector('.ribbon-satin'),MAGENTA=[233,0,141],ORANGE=[253,166,61],WHITE=[255,255,255];
const mixRgb=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t);
// Sample the ribbon path in JS: getPointAtLength() costs ~1 ms per call and blocked page load for seconds.
// Our paths use only absolute M, C and L commands, so we flatten them into a polyline and walk it by distance.
function flatten(d){
  const tok=d.match(/[MCL]|-?\d*\.?\d+(?:e[-+]?\d+)?/g),pts=[];let i=0,cmd='',x=0,y=0;
  while(i<tok.length){
    if(/[MCL]/.test(tok[i]))cmd=tok[i++];
    if(cmd==='M'||cmd==='L'){x=+tok[i++];y=+tok[i++];pts.push([x,y]);}
    else{const[a,b,c,e,f,g]=tok.slice(i,i+6).map(Number);i+=6;
      const n=Math.max(8,Math.ceil((Math.hypot(a-x,b-y)+Math.hypot(c-a,e-b)+Math.hypot(f-c,g-e))/12));
      for(let k=1;k<=n;k++){const t=k/n,u=1-t;pts.push([u*u*u*x+3*u*u*t*a+3*u*t*t*c+t*t*t*f,u*u*u*y+3*u*u*t*b+3*u*t*t*e+t*t*t*g]);}
      x=f;y=g;}
  }
  const cum=[0];for(let k=1;k<pts.length;k++)cum.push(cum[k-1]+Math.hypot(pts[k][0]-pts[k-1][0],pts[k][1]-pts[k-1][1]));
  let j=0;
  return{length:cum[cum.length-1],at(s){ // s must not decrease between calls
    while(j<cum.length-2&&cum[j+1]<s)j++;
    const t=(s-cum[j])/((cum[j+1]-cum[j])||1),[x0,y0]=pts[j],[x1,y1]=pts[j+1]||pts[j];
    return[x0+(x1-x0)*t,y0+(y1-y0)*t];}};
}
// Paints a satin ribbon along path d into group g (used by the page ribbon and the footer team).
// ring (page ribbon only): between distances ring.from and ring.to the ribbon coils around the About ball. There it is
// flat and a little wider, with one twist on the way in and one on the way out, and its near half goes to ring.g,
// which is drawn over the ball.
function paintSatin(g,d,mobile,fadeEnd=true,ring=null){
  const step=mobile?5:7,maxW=mobile?8:12,flip=mobile?220:320,hue=mobile?1100:1600,pts=[];
  const walk=flatten(d),length=walk.length;
  for(let s=0;s<=length;s+=step){const[x,y]=walk.at(s);pts.push([x,y,s]);}
  const n=pts.length-1,layers=[[],[]],f=q=>q[0].toFixed(1)+','+q[1].toFixed(1);
  const L=mobile?100:140,inRing=s=>ring&&s>ring.from&&s<ring.to,twist=[0];let rate=0;
  for(let i=1;i<=n;i++){
    const s=pts[i][2];let dt=step/flip*Math.PI;
    // Entry: settle on the front face (a multiple of 2π); coming from the back face that passes one narrow point.
    if(inRing(s)&&s<ring.from+L&&!rate){const r=(twist[i-1]%(2*Math.PI)+2*Math.PI)%(2*Math.PI);rate=(r<=Math.PI?-r:2*Math.PI-r)/L||1e-9;}
    if(inRing(s))dt=s<ring.from+L?rate*step:s>ring.to-L?Math.PI/L*step:0;
    twist.push(twist[i-1]+dt);
  }
  const edge=i=>{
    const a=pts[Math.max(0,i-1)],b=pts[Math.min(n,i+1)],dx=b[0]-a[0],dy=b[1]-a[1],l=Math.hypot(dx,dy)||1,s=pts[i][2];
    const wide=inRing(s)?1+.3*Math.min(1,(s-ring.from)/L,(ring.to-s)/L):1;
    const c=Math.cos(twist[i]),w=maxW*wide*(.12+.88*Math.abs(c))/2,[x,y]=pts[i];
    return{a:[x-dy/l*w,y+dx/l*w],b:[x+dy/l*w,y-dx/l*w],c,s};
  };
  let prev=edge(0);
  for(let i=1;i<=n;i++){
    const cur=edge(i),lit=Math.abs(cur.c);
    let col=mixRgb(MAGENTA,ORANGE,.5-.5*Math.cos(cur.s/hue*2*Math.PI));
    if(cur.c<0)col=mixRgb(col,WHITE,.28);
    col=col.map(v=>v*(.72+.28*lit));
    if(lit>.92)col=mixRgb(col,WHITE,.22*(lit-.92)/.08);
    const fade=fadeEnd?Math.min(1,(length-cur.s)/(mobile?160:260)).toFixed(1):'1.0',key=col.map(v=>Math.round(v/6)*6).join(',')+'|'+fade,quad=`M${f(prev.a)}L${f(cur.a)}L${f(cur.b)}L${f(prev.b)}Z`;
    const runs=layers[inRing(cur.s)&&ring.front(pts[i])?1:0];
    if(runs.length&&runs[runs.length-1][0]===key)runs[runs.length-1][1]+=quad;else runs.push([key,quad]);prev=cur;
  }
  const paths=runs=>runs.map(([rgb,d])=>{
    const path=document.createElementNS('http://www.w3.org/2000/svg','path');
    const [c,o]=rgb.split('|');path.setAttribute('d',d);path.setAttribute('fill',`rgb(${c})`);path.setAttribute('stroke',`rgb(${c})`);path.setAttribute('stroke-width','.6');if(o<1)path.setAttribute('opacity',o);
    return path;
  });
  g.replaceChildren(...paths(layers[0]));
  if(ring)ring.g.replaceChildren(...paths(layers[1]));
}
function layoutRibbon(){
  if(!ribbon||!document.querySelector('.hero-photo')||!document.querySelector('.gymnast-art')||!document.querySelector('.ribbon-anchor')||!document.querySelector('.closing'))return;
  const width=main.clientWidth,height=main.offsetHeight,mobile=width<=760,mainTop=main.getBoundingClientRect().top;
  const bounds=el=>{const r=el.getBoundingClientRect();return{x:r.left-main.getBoundingClientRect().left,y:r.top-mainTop,w:r.width,h:r.height};};
  const photo=bounds(document.querySelector('.hero-photo')),left=width*(mobile?.025:.035),right=width*(mobile?.975:.965);
  const art=bounds(document.querySelector('.gymnast-art')),anchor=bounds(document.querySelector('.ribbon-anchor'));
  const startX=anchor.x+anchor.w/2,startY=anchor.y+anchor.h/2;
  const gradient=ribbon.querySelector('linearGradient');
  Object.entries({gradientUnits:'userSpaceOnUse',x1:photo.x,y1:photo.y,x2:photo.x+photo.w,y2:photo.y+photo.h}).forEach(([key,value])=>gradient.setAttribute(key,value));
  let x=right,y=photo.y+photo.h+25,ring=null;
  // Leave the stick tip along the stick (up and to the right), then sweep to the right edge.
  let d=`M ${startX} ${startY} C ${startX+art.h*.05} ${startY-art.h*.14} ${right} ${startY-art.h*.1} ${right} ${art.y+art.h*.43} C ${right} ${art.y+art.h*.7} ${x} ${y-40} ${x} ${y}`;
  [...main.querySelectorAll(':scope > section')].slice(1).filter(el=>el.getClientRects().length>0&&!el.classList.contains('closing')).forEach((section,index)=>{
    const box=bounds(section),transitionY=box.y+(mobile?47:65),nextX=section.id==='about'?left:index%2===0?left:right;
    const mid=width*.5,spread=width*(mobile?.23:.27),loop=mobile?32:49;
    // Wide E-like loops live inside reserved whitespace above each section.
    const entryX=x<mid?width*.14:width*.86;
    const approachY=transitionY-loop-12;
    d+=` C ${x} ${y+45} ${x} ${approachY-35} ${x} ${approachY} C ${x} ${transitionY-15} ${entryX} ${transitionY-15} ${entryX} ${transitionY-15}`;
    d+=` C ${mid} ${transitionY-15} ${mid-spread} ${transitionY-loop} ${mid} ${transitionY-loop} C ${mid+spread} ${transitionY-loop} ${mid+spread} ${transitionY+loop} ${mid} ${transitionY+loop} C ${mid-spread} ${transitionY+loop} ${nextX} ${transitionY+20} ${nextX} ${transitionY+65}`;
    x=nextX;y=transitionY+65;
    if(section.id==='about'){
      // The ribbon coils around the ball like a hoop seen from above, tilted -17°: it comes down onto the ring's left end,
      // makes 1¼ turns (the second turn lower and slightly right, far enough that the scroll reveal of one pass doesn't uncover the next) and leaves from the bottom, down and right.
      // Points of the ring's near (lower) half in front of the ball are painted over it; the rest keeps the plain paint order.
      const art=bounds(section.querySelector('.about-art')),R=Math.min(art.w,art.h)*(mobile?.2:.18),cx=art.x+art.w/2,cy=art.y+art.h/2;
      const phi=-17*Math.PI/180,cs=Math.cos(phi),sn=Math.sin(phi),turns=1.25,N=120;
      const at=(t,p)=>{const u=1.5*R*Math.cos(t)+R*(.1*p-.05),v=.6*R*Math.sin(t)+R*(.6*p-.3);return[cx+u*cs-v*sn,cy+u*sn+v*cs];};
      const ball=ribbon.querySelector('.ball'),shade=ribbon.querySelector('.ball-shadow');
      Object.entries({cx,cy,r:R}).forEach(([k,v])=>ball.setAttribute(k,v));
      Object.entries({cx:cx+R*.12,cy:cy+R*1.45,rx:R*1.15,ry:R*.2}).forEach(([k,v])=>shade.setAttribute(k,v));
      const p0=at(Math.PI,0),from=flatten(d+=` C ${x} ${(y+p0[1])/2} ${p0[0]+110*sn} ${p0[1]-110*cs} ${p0[0]} ${p0[1]}`).length;
      let coil=`M ${p0[0]} ${p0[1]}`;
      for(let k=1;k<=N;k++){const q=at(Math.PI-turns*2*Math.PI*k/N,k/N);coil+=` L ${q[0].toFixed(1)} ${q[1].toFixed(1)}`;}
      d+=coil.slice(coil.indexOf(' L'));
      const pe=at(Math.PI-turns*2*Math.PI,1),pp=at(Math.PI-turns*2*Math.PI*(N-1)/N,(N-1)/N),dl=Math.hypot(pe[0]-pp[0],pe[1]-pp[1]);
      const endX=mobile?right:(art.x+art.w+bounds(section.querySelector('.about-copy')).x)/2,endY=art.y+art.h;
      const to=flatten(d).length+(mobile?100:140);
      d+=` C ${pe[0]+(pe[0]-pp[0])/dl*90} ${pe[1]+(pe[1]-pp[1])/dl*90} ${endX} ${endY-90} ${endX} ${endY}`;
      ring={from:from-(mobile?100:140),to,g:ribbon.querySelector('.ribbon-front'),front:([px,py])=>(py-cy)*cs-(px-cx)*sn>0&&Math.abs((px-cx)*cs+(py-cy)*sn)<1.15*R};
      ribbon.querySelector('.ring-shadow').setAttribute('d',coil);
      ribbon.querySelector('.ring-shadow').setAttribute('transform',mobile?'translate(2 5)':'translate(3 7)');
      x=endX;y=endY;
    }
  });
  // Finale: the ribbon sweeps down the right side of the dark closing section and slips behind the footer at the right edge
  // (the SVG ends at the bottom of <main>, so everything below is hidden by the footer's top edge).
  const finale=bounds(document.querySelector('.closing'));
  // Down the current side, then cross to the right edge in the gap just above the closing section.
  d+=` C ${x} ${y+40} ${x} ${finale.y-110} ${x} ${finale.y-70} C ${x} ${finale.y-20} ${right} ${finale.y-40} ${right} ${finale.y+20}`;
  if(mobile)d+=` C ${right} ${finale.y+finale.h*.5} ${right} ${height-40} ${right} ${height+140}`;
  else d+=` C ${right} ${finale.y+finale.h*.3} ${finale.x+finale.w*.62} ${finale.y+finale.h*.4} ${finale.x+finale.w*.72} ${finale.y+finale.h*.62} C ${finale.x+finale.w*.8} ${finale.y+finale.h*.82} ${right} ${height-60} ${right} ${height+140}`;
  ribbon.setAttribute('viewBox',`0 0 ${width} ${height}`);ribbonLine.setAttribute('d',d);
  const walk=flatten(d),length=walk.length,samples=[];paintSatin(satin,d,mobile,true,ring);
  // Bound sampling work even as content makes the page longer.
  const sampleStep=Math.max(24,length/160);
  for(let distance=0;distance<=length;distance+=sampleStep)samples.push({distance,y:walk.at(distance)[1]});
  const range=document.documentElement.scrollHeight-innerHeight,documentTop=mainTop+scrollY,frames=[];let cursor=0;
  for(let percent=0;percent<=100;percent++){
    const target=percent===0?photo.y+photo.h*.5:range*percent/100+innerHeight*.75-documentTop;
    while(cursor<samples.length-1&&samples[cursor].y<target)cursor++;
    frames.push(`${percent}%{stroke-dashoffset:${percent===100?0:Math.max(0,1000*(1-samples[cursor].distance/length)).toFixed(3)}}`);
  }
  ribbonTiming.textContent=`@keyframes ribbon-unfold{${frames.join('')}}`;positionSpark();
}
// Gallery photos and the founder's portrait pop in the first time their block comes into view. Video band: the decorative loop plays
// only while on screen. With reduced motion neither moves: the gallery stands still and the video stays on its poster.
const calm=matchMedia('(prefers-reduced-motion: reduce)').matches,loop=document.querySelector('.video-loop');
if(!calm)document.querySelectorAll('.gallery,.coaches').forEach(block=>{const target=block.querySelector('.gallery-grid,.founder');if(!target)return;block.classList.add('reveal-ready');new IntersectionObserver(([e],io)=>{if(e.isIntersecting){block.classList.add('is-in');io.disconnect();}},{threshold:.2}).observe(target);});
if(loop){if(calm){loop.removeAttribute('autoplay');loop.load();}else new IntersectionObserver(([e])=>e.isIntersecting?loop.play().catch(()=>{}):loop.pause()).observe(loop);}

// The team under the founder: one card per coach in the #team-data array ({name, role, focus, photo, alt, bio}; photo paths
// start with "/" so they work on /ru/ and /uk/ too). Empty array: the block stays hidden. One coach: a wide card over two
// columns; more: 3 columns on desktop, 2 on tablets, 1 on phones (site.css).
const teamBlock=document.querySelector('.team-block'),coaches=JSON.parse(document.querySelector('#team-data')?.textContent||'[]');
if(teamBlock&&coaches.length){
  const card=document.querySelector('#team-card').content.firstElementChild;
  teamBlock.querySelector('.team-list').append(...coaches.map(c=>{
    const li=card.cloneNode(true),photo=li.querySelector('.team-photo');
    if(c.photo){const img=new Image(400,400);img.src=c.photo;img.alt=c.alt||'';img.loading='lazy';photo.append(img);}else photo.classList.add('is-empty');
    li.querySelector('h4').textContent=c.name;li.querySelector('.team-role').textContent=c.role;li.querySelector('.team-focus').textContent=c.focus;
    const bio=li.querySelector('.team-bio');bio.textContent=c.bio||'';bio.closest('details').hidden=!c.bio;
    return li;
  }));
  teamBlock.hidden=false;
  // With a team the eyebrow switches from the founder-only wording to the team wording (both spans live in about/index.html).
  document.querySelector('.coach-eyebrow-solo')?.setAttribute('hidden','');document.querySelector('.coach-eyebrow-team')?.removeAttribute('hidden');
}

// About: the ribbon girl's satin ribbon trails from her stick tip (path in data-d, drawn in a scale(4) group).
document.querySelectorAll('.apparatus-satin').forEach(g=>paintSatin(g,g.dataset.d,false,false));

// Contact prototype: validate locally; never simulate successful delivery.
const contactForm=document.querySelector('#contact-form');
if(contactForm){
  const fields=[...contactForm.querySelectorAll('input,textarea')],status=contactForm.querySelector('#contact-status');
  function contactValid(field){
    const value=field.value.trim();
    if(!value||value.length>field.maxLength)return false;
    if(field.name==='email')return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
    if(field.name==='phone')return /^[+\d\s().-]+$/.test(value)&&/^\d{10,15}$/.test(value.replace(/\D/g,''));
    return true;
  }
  function showContactError(field,invalid){
    field.setAttribute('aria-invalid',String(invalid));
    document.getElementById(field.getAttribute('aria-describedby')).hidden=!invalid;
  }
  fields.forEach(field=>field.addEventListener('input',()=>{
    status.hidden=true;
    if(field.getAttribute('aria-invalid')==='true')showContactError(field,!contactValid(field));
  }));
  contactForm.addEventListener('submit',event=>{
    event.preventDefault();status.hidden=true;
    fields.forEach(field=>showContactError(field,!contactValid(field)));
    const invalid=fields.find(field=>!contactValid(field));
    if(invalid){invalid.focus();return;}
    status.hidden=false;status.focus();
  });
}

// Footer team: a row of little gymnasts (traced sprite assets/gymnast/team.svg, one shared scale, feet on one floor).
// The satin ribbon is strung between the sticks of the two end girls and waves over the others' heads.
// A named view timeline on .footer-team makes the girls rise in one by one and draws the ribbon from right to left.
// Girls grow with the width (120–240 px) and the row holds as many as fit (5 at 320 px, 12 from 760 px): docs/footer-team.en.md.
const team=document.querySelector('.footer-team');
const teamSprite=new URL('assets/gymnast/team.svg',document.querySelector('link[href$="site.css"]').href).href;
const KIDS={1:[196,708],2:[414,618],3:[369,649],4:[305,608],5:[401,627],6:[410,693,8,6],7:[323,635],8:[357,626],9:[314,631],10:[347,659],11:[395,659],12:[282,745,24,6]};
const TEAM_PRIORITY=[12,6,1,3,10,5,7,2,8,11,4,9],TEAM_ORDER=[12,1,3,7,10,2,5,8,11,4,9,6];
function layoutTeam(){
  if(!team)return;
  const W=team.clientWidth,mobile=innerWidth<=760;
  const kidH=Math.min(240,Math.max(120,.19*W)),sc=kidH/745,pad=kidH/20;
  // Equal cells, at least 0.42 of a girl's height wide: as many as fit (4–12), each girl centred in hers.
  // The two holding sticks always stand at the ends.
  const n=Math.max(4,Math.min(12,Math.floor((W-2*pad)/(.42*kidH)))),cell=(W-2*pad)/n;
  const order=TEAM_PRIORITY.slice(0,n).sort((a,b)=>TEAM_ORDER.indexOf(a)-TEAM_ORDER.indexOf(b));
  const top=.15*kidH,H=kidH+top+4,floor=H-2,amp=.075*kidH;
  const kids=order.map((k,i)=>{const[w,h,tx,ty]=KIDS[k],x=pad+i*cell+(cell-w*sc)/2;return{k,x,y:floor-h*sc,w:w*sc,h:h*sc,tip:tx===undefined?null:[x+tx*sc,floor-h*sc+ty*sc]};});
  const tipL=kids[0].tip,tipR=kids[kids.length-1].tip;
  // Through-points right to left: a wave above the heads, dipping in the gaps between the girls.
  const P=[tipR];
  for(let i=kids.length-2;i>=1;i--){const k=kids[i];P.push([k.x+k.w/2,top*.5+(i%2?amp:-amp*.4)]);}
  P.push(tipL);
  let d=`M ${P[0][0].toFixed(1)} ${P[0][1].toFixed(1)}`;
  for(let i=0;i<P.length-1;i++){const a=P[Math.max(0,i-1)],b=P[i],c=P[i+1],e=P[Math.min(P.length-1,i+2)];
    d+=` C ${(b[0]+(c[0]-a[0])/6).toFixed(1)} ${(b[1]+(c[1]-a[1])/6).toFixed(1)} ${(c[0]-(e[0]-b[0])/6).toFixed(1)} ${(c[1]-(e[1]-b[1])/6).toFixed(1)} ${c[0].toFixed(1)} ${c[1].toFixed(1)}`;}
  team.innerHTML=`<svg class="team" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" aria-hidden="true" focusable="false">
    <defs><mask id="team-reveal" maskUnits="userSpaceOnUse" x="-80" y="-80" width="${W+160}" height="${H+160}"><path class="team-reveal" pathLength="1" d="${d}"/></mask></defs>
    ${kids.map((k,i)=>`<use class="team-kid" href="${teamSprite}#kid-${k.k}" x="${k.x.toFixed(1)}" y="${k.y.toFixed(1)}" width="${k.w.toFixed(1)}" height="${k.h.toFixed(1)}" style="animation-range:entry ${10+i*4}% entry ${45+i*4}%"/>`).join('')}
    <g class="team-ribbon" mask="url(#team-reveal)"></g></svg>`;
  paintSatin(team.querySelector('.team-ribbon'),d,mobile,false);
}
let layoutFrame;
function scheduleLayout(){cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>{layoutRibbon();layoutTeam();});}
new ResizeObserver(scheduleLayout).observe(main);window.addEventListener('resize',scheduleLayout);document.fonts.ready.then(scheduleLayout);scheduleLayout();
